### ISSUE TITLE
DEAccountContants fails to import in python 3.6 version of 1.2 branch.

### ISSUE THREAD

**Issue by StevenCTimm** [HEPCloud/decisionengine_modules#224]
In the AWSBilling channel we get the following error in startup:

2020-05-13 16:22:23,833 - decision_engine - ConfigManager - Thread-6 - ERROR - AWSbilling No module named 'DEAccountContants', REMOVING the channel

[root@fermicloud117 sources]# python3 DEAccountContants.py
Traceback (most recent call last):
  File "DEAccountContants.py", line 71, in <module>
    account_dict = load_constants('AccountConstants_sample.py')
  File "DEAccountContants.py", line 63, in load_constants
    code = "config_dict=" + string.join(f.readlines(), "")
AttributeError: module 'string' has no attribute 'join'

----

DEAccountContants is imported by BillingInfo.py 
Both of these are in AWS/sources

**Comment by DmitryLitvintsev** [comment]
https://fermicloud140.fnal.gov/reviews/r/124

**Comment by StevenCTimm** [comment]
As of the latest CI rpm build of today this error is still not fixed.

**Comment by DmitryLitvintsev** [comment]
Sorry, my bad. Somehow it slipped. Fixed now.

**Comment by StevenCTimm** [comment]
Installed the latest pre-release generated in CI, this channel starts OK.. just hold this open until such time as the 1.2 release is cut.

**Comment by StevenCTimm** [comment]
In the new release it imports OK but there is something wrong with AWSbilling channel 
(BillingInfo.py) so want to hold this open until we are sure that is clear.

**Comment by DmitryLitvintsev** [comment]
Can you clarify. Where you first installed it 7 days ago and import was working. Was there something along with AWSbilling channel (BillingInfo.py). Or this happened only now in 1.2 release?

**Comment by StevenCTimm** [comment]
The import worked 7 days ago in the pre-release and it is still working now. but there's something else higher in the channel that's not working (and has never worked on python 3.6 as far as I known)  and I want to be sure about what that is--once I figure out I will file a different bug and we can close this one.

**Comment by StevenCTimm** [comment]
The new error is now tracked in issue #240.  This one can be closed.. thank you
